;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Лабиринт (В стиле РобоКап)]
Pos=10,10
Size=540,540
Collapsed=0

[Window][Камера / Метки ИИ]
Pos=560,10
Size=370,740
Collapsed=0

[Window][Терминал Ввода (Входящие UDP пакеты)]
Pos=10,560
Size=540,190
Collapsed=0

[Docking][Data]


;;;<<<Layout_655921752_Default>>>;;;

;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker

;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
