[platformio]
src_dir = firmware/

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_speed = 115200
lib_deps =
    sstaub/Ticker@^4.4.0
    electroniccats/MPU6050@^1.4.4
    hideakitai/DebugLog@^0.8.4
    pololu/VL53L0X@^1.3.1
    bxparks/AceSorting@^1.0.0