[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_speed = 115200
lib_deps =
    sstaub/Ticker@^4.4.0
    adafruit/Adafruit BNO055@^1.6.4
    hideakitai/DebugLog@^0.8.4
    pololu/VL53L0X@^1.3.1
    bxparks/AceSorting@^1.0.0
    adafruit/Adafruit TCS34725@^1.4.4
    gyverlibs/microLED@^3.6
    fastled/FastLED@^3.9.11
    arduino-libraries/Servo@^1.3.0
    gyverlibs/uButton@^1.1.2
    gyverlibs/GyverWDT@^2.3.1
    etlcpp/Embedded Template Library@^20.48.1
    etlcpp/Embedded Template Library - Arduino@^20.38.2

upload_flags =
    -V
    -q

build_flags =
    -DETL_NO_STL
    -DDEBUGLOG_DEFAULT_LOG_LEVEL_TRACE

lib_ldf_mode = chain